<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQEZfYex\srcApp_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQEZfYex/srcApp_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQEZfYex.legacy');

    return;
}

if (!\class_exists(srcApp_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQEZfYex\srcApp_KernelProdContainer::class, srcApp_KernelProdContainer::class, false);
}

return new \ContainerQEZfYex\srcApp_KernelProdContainer([
    'container.build_hash' => 'QEZfYex',
    'container.build_id' => 'fc1d3e4f',
    'container.build_time' => 1626023868,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQEZfYex');
