<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBxxrMTE\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBxxrMTE/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBxxrMTE.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBxxrMTE\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerBxxrMTE\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'BxxrMTE',
    'container.build_id' => '6092e7ab',
    'container.build_time' => 1626359258,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBxxrMTE');
